# Generated by Django 4.2.7 on 2023-11-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=300)),
                ('item_type', models.CharField(choices=[('S', 'S'), ('M', 'M')], max_length=1)),
                ('year_released', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('price_new', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_new', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.item')),
            ],
        ),
    ]
