# Generated by Django 4.2.7 on 2023-11-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('item', 'date')},
        ),
    ]
