# Generated by Django 4.2.7 on 2023-11-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_price_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='qty_new',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='qty_used',
            field=models.IntegerField(),
        ),
    ]
