# Generated by Django 4.2.7 on 2023-11-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_price_qty_new_alter_price_qty_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_path',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
