# Generated by Django 4.2.7 on 2023-12-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_item_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('bought_for', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_acquired', models.DateField()),
                ('notes', models.CharField(max_length=300)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
        ),
    ]
